from sqlalchemy import String, Text, Float, Integer, Boolean, DateTime, JSON, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from .core import Base, utcnow

class Source(Base):
 __tablename__='sources'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(200)); url:Mapped[str]=mapped_column(Text,unique=True); country:Mapped[str|None]=mapped_column(String(80)); categories:Mapped[list]=mapped_column(JSON,default=list); languages:Mapped[list]=mapped_column(JSON,default=list); source_type:Mapped[str]=mapped_column(String(50),default='website'); trust:Mapped[float]=mapped_column(Float,default=.7); active:Mapped[bool]=mapped_column(Boolean,default=True); last_crawled:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True))
class Campaign(Base):
 __tablename__='campaigns'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text,default=''); cadence:Mapped[str]=mapped_column(String(20),default='weekly'); cron:Mapped[str|None]=mapped_column(String(100)); queries:Mapped[list]=mapped_column(JSON,default=list); languages:Mapped[list]=mapped_column(JSON,default=lambda:['en']); filters:Mapped[dict]=mapped_column(JSON,default=dict); enabled:Mapped[bool]=mapped_column(Boolean,default=True); next_run:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[DateTime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Opportunity(Base):
 __tablename__='opportunities'; id:Mapped[int]=mapped_column(primary_key=True); fingerprint:Mapped[str]=mapped_column(String(64),unique=True,index=True); title:Mapped[str]=mapped_column(Text); organizer:Mapped[str]=mapped_column(Text,default=''); url:Mapped[str]=mapped_column(Text); official_url:Mapped[str|None]=mapped_column(Text); kind:Mapped[str]=mapped_column(String(50),default='other'); summary:Mapped[str]=mapped_column(Text,default=''); categories:Mapped[list]=mapped_column(JSON,default=list); skills:Mapped[list]=mapped_column(JSON,default=list); countries:Mapped[list]=mapped_column(JSON,default=list); remote:Mapped[bool|None]=mapped_column(Boolean); reward:Mapped[float|None]=mapped_column(Float); currency:Mapped[str|None]=mapped_column(String(8)); deadline:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True)); eligibility:Mapped[str]=mapped_column(Text,default=''); evidence:Mapped[dict]=mapped_column(JSON,default=dict); confidence:Mapped[float]=mapped_column(Float,default=.5); trust:Mapped[float]=mapped_column(Float,default=.5); first_seen:Mapped[DateTime]=mapped_column(DateTime(timezone=True),default=utcnow); last_seen:Mapped[DateTime]=mapped_column(DateTime(timezone=True),default=utcnow); status:Mapped[str]=mapped_column(String(20),default='open')
class Run(Base):
 __tablename__='runs'; id:Mapped[int]=mapped_column(primary_key=True); campaign_id:Mapped[int]=mapped_column(ForeignKey('campaigns.id')); status:Mapped[str]=mapped_column(String(20),default='queued'); stats:Mapped[dict]=mapped_column(JSON,default=dict); started_at:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True)); finished_at:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True)); error:Mapped[str|None]=mapped_column(Text)
class Profile(Base):
 __tablename__='profiles'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(100)); skills:Mapped[list]=mapped_column(JSON,default=list); interests:Mapped[list]=mapped_column(JSON,default=list); countries:Mapped[list]=mapped_column(JSON,default=list); min_reward:Mapped[float]=mapped_column(Float,default=0); hours_per_week:Mapped[int]=mapped_column(Integer,default=10)
class Match(Base):
 __tablename__='matches'; id:Mapped[int]=mapped_column(primary_key=True); profile_id:Mapped[int]=mapped_column(ForeignKey('profiles.id')); opportunity_id:Mapped[int]=mapped_column(ForeignKey('opportunities.id')); score:Mapped[float]=mapped_column(Float); reasons:Mapped[list]=mapped_column(JSON,default=list)
