from sqlalchemy import String,Text,Float,Integer,Boolean,DateTime,JSON,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from .core import Base,utcnow

class AdapterCursor(Base):
 __tablename__='adapter_cursors';id:Mapped[int]=mapped_column(primary_key=True);adapter:Mapped[str]=mapped_column(String(80));query:Mapped[str]=mapped_column(Text,default='');cursor:Mapped[dict]=mapped_column(JSON,default=dict);last_started:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True));last_success:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True));last_error:Mapped[str|None]=mapped_column(Text);consecutive_errors:Mapped[int]=mapped_column(Integer,default=0);__table_args__=(UniqueConstraint('adapter','query'),)
class ProgramFamily(Base):
 __tablename__='program_families';id:Mapped[int]=mapped_column(primary_key=True);key:Mapped[str]=mapped_column(String(64),unique=True,index=True);name:Mapped[str]=mapped_column(Text);organizer:Mapped[str]=mapped_column(Text,default='');kind:Mapped[str]=mapped_column(String(50),default='other');members:Mapped[int]=mapped_column(Integer,default=0);interval_days:Mapped[float|None]=mapped_column(Float);interval_std_days:Mapped[float|None]=mapped_column(Float);next_expected:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True),index=True);window_start:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True));window_end:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True));confidence:Mapped[float]=mapped_column(Float,default=0);features:Mapped[dict]=mapped_column(JSON,default=dict);updated_at:Mapped[DateTime]=mapped_column(DateTime(timezone=True),default=utcnow)
class PredictiveAlert(Base):
 __tablename__='predictive_alerts';id:Mapped[int]=mapped_column(primary_key=True);family_key:Mapped[str]=mapped_column(String(64),index=True);kind:Mapped[str]=mapped_column(String(40),default='expected_reopening');message:Mapped[str]=mapped_column(Text);expected_at:Mapped[DateTime|None]=mapped_column(DateTime(timezone=True));confidence:Mapped[float]=mapped_column(Float,default=0);created_at:Mapped[DateTime]=mapped_column(DateTime(timezone=True),default=utcnow);read:Mapped[bool]=mapped_column(Boolean,default=False);__table_args__=(UniqueConstraint('family_key','kind','expected_at'),)
